--- 
images: 
  simon020286/caddy: 
    path: caddy
    platforms: 
      - linux/arm/v7
  simon020286/transmission: 
    path: transmission
    platforms: 
      - linux/arm/v7
  simon020286/sqlite3:
    path: sqlite
    platforms:
      - linux/arm/v7
path: "D:\\Projects\\docker"